### ISSUE TITLE
Creating the Papers txt File

### ISSUE THREAD

**Issue by m1k2zoo** [nd7141/icml2020#2]
Just wondering how you were able to extract the affiliations for each paper to add them to your text file? I am trying to perform a similar analysis for other conferences.

**Comment by nd7141** [comment]
You can see in the list of papers there are affiliations for each author. I took the content inside the brackets. To map it to some standard name i have a bunch of heuristics, which is not perfect. I found mapping different affiliations to the same standard name is the most complicated part.
